### ISSUE TITLE
Cara fix `ValidatorInterface` error saat menambahkan petugas saat menggunakan CI 4.5.x

### ISSUE THREAD

**Issue by ikhsan3adi** [ikhsan3adi/absensi-sekolah-qr-code#66]
### Cara pertama

Download source code dari [branch `temp-auth-fix`](https://github.com/ikhsan3adi/absensi-sekolah-qr-code/tree/temp-auth-fix)

### Cara kedua

Untuk sementara, update file `vendor/myth/auth/src/Authentication/Passwords/ValidatorInterface.php`

```php
#use CodeIgniter\Entity;
use CodeIgniter\Entity\Entity;
```

sumber:
https://github.com/lonnieezell/myth-auth/issues/621#issue-2241692427

**Comment by pedangmujahid** [comment]
use CodeIgniter\Entity\Entity;
use Myth\Auth\Exceptions\AuthException;


kalau dah guna yang ini tapi masih ada error yang sama.. > macam mana nak check..?>


Could not check compatibility between Myth\Auth\Authentication\Passwords\CompositionValidator::check(string $password, ?CodeIgniter\Entity\Entity $user = null): bool and Myth\Auth\Authentication\Passwords\ValidatorInterface::check(string $password, ?CodeIgniter\Entity $user = null): bool, because class CodeIgniter\Entity is not available [search →](https://www.duckduckgo.com/?q=ErrorException+Could+not+check+compatibility+between+Myth%5CAuth%5CAuthentication%5CPasswords%5CCompositionValidator%3A%3Acheck%28string+%24password%2C+%3FCodeIgniter%5CEntity%5CEntity+%24user+%3D+null%29%3A+bool+and+Myth%5CAuth%5CAuthentication%5CPasswords%5CValidatorInterface%3A%3Acheck%28string+%24password%2C+%3FCodeIgniter%5CEntity+%24user+%3D+null%29%3A+bool%2C+because+class+CodeIgniter%5CEntity+is+not+available)
